# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               '> Skyepaphora Griffith <'
tagline:             '"something mathy"'
description:         'Isn't this neat'
baseurl:             ''
paginate:            5
markdown:            kramdown

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# About/contact
author:
  name:              Your Name
  url:               https://skyepaphora.github.io
  email:             youremail@email.com

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/codebam/tmsc-workshop
